services:
  postgres17:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=engsel
    ports:
      - 5432:5432
    restart: always
