name: Node.js 20.17

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.x"
      - run: docker compose up -d
      - run: npm ci
      - run: cp .env.github .env
      - run: npx prisma generate
      - run: npx prisma migrate deploy
      - run: npx prisma db seed
      - run: MIDTRANS_SERVER_KEY=${{ secrets.MIDTRANS_SERVER_KEY }} SMTP_HOST=${{ secrets.SMTP_HOST }} SMTP_PORT=${{ secrets.SMTP_PORT }} SMTP_USER=${{ secrets.SMTP_USER }} SMTP_PASS=${{ secrets.SMTP_PASS }} npm test
      - run: npm run build
      - run: docker compose down
